### PR TITLE
Enable d_type for OverlayFS support

### PR DESCRIPTION
**Pull request by ghost**
OverlayFS is now supported for docker in RHEL 7.4

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.4_Release_Notes/technology_previews_file_systems.html

```Full support is available for OverlayFS when used with Docker under the following restrictions:
OverlayFS is only supported for use as a Docker graph driver. Its use can only be supported for container COW content, not for persistent storage. Any persistent storage must be placed on non-OverlayFS volumes to be supported. Only default Docker configuration can be used; that is, one level of overlay, one lowerdir, and both lower and upper levels are on the same file system```

### CODE REVIEW

**Comment by ghost** [comment]
this fixes issue #2

**Comment by pgporada** [comment]
Man oh man that would have been useful to me last year :P

**Comment by bashtoni** [comment]
Thanks @pavloos, but I'm confused as to whether this is actually necessary.

The xfs man page says `ftype=1` is the default, and running `xfs_info` on a root volume for a machine created from this AMI suggests this is already set:

```
meta-data=/dev/xvda2             isize=512    agcount=9, agsize=327488 blks
         =                       sectsz=512   attr=2, projid32bit=1
         =                       crc=1        finobt=0 spinodes=0
data     =                       bsize=4096   blocks=2620923, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0 ftype=1
log      =internal               bsize=4096   blocks=2560, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
```

Am I missing something here?

**Comment by ghost** [comment]
Perfect, RH must have changed defaults, it wasn't default on 7.3. Closing.

**Pull request closed without merging**
